# Generated by Django 4.2.5 on 2023-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_method_payment_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='datetime_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('loading', 'loading'), ('cancel', 'cancel'), ('success', 'success')], default='loading'),
        ),
    ]
