# Generated by Django 4.2.5 on 2023-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_datetime_payment_payment_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verify_payment_number',
            field=models.PositiveIntegerField(default=80808080, verbose_name='verify payment number'),
            preserve_default=False,
        ),
    ]
