# Generated by Django 4.2.5 on 2023-09-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=100000, verbose_name='price'),
            preserve_default=False,
        ),
    ]
